### ISSUE TITLE
Support user-specified HTML getters

### ISSUE THREAD

**Issue by kentcdodds** [MichaelDeBoey/gatsby-remark-embedder#1]
I don't know how the configuration would look, but my original idea was to allow for customization of this:

https://github.com/MichaelDeBoey/gatsby-remark-embedder/blob/869dc65a01629cfa89d4e89e2fc6eae440f1c656/src/index.js#L7

via some sort of configuration. That way people could add their own embedder transforms without requiring any changes within this project.

**Comment by MichaelDeBoey** [comment]
Superseded by #42
