### ISSUE TITLE
Youtube channel links are broken

### ISSUE THREAD

**Issue by lekterable** [MichaelDeBoey/gatsby-remark-embedder#10]
- `gatsby-remark-embedder` version: 1.1.2
- `node` version: v10.16.0
- `npm` (or `yarn`) version: 6.9.0

What you did:

Pasted a link to a youtube channel in a markdown document

What happened:

Link is transformed into an iframe which is broken

<img width="598" alt="Screenshot 2019-09-13 at 12 48 43" src="https://user-images.githubusercontent.com/23037261/64857570-343c1e80-d625-11e9-9851-c49d4a84c667.png">

Suggested solution:

I'm not sure if there's a way of embedding youtube channels, if there is I would use if not I would make the plugin ignore those links.

**Comment by MichaelDeBoey** [comment]
Hi @lekterable!

Thanks for reporting this.

Can you provide me with a reproduction link (CodeSandbox) or repo so I can dig into this further, please? 🤔

**Comment by MichaelDeBoey** [comment]
Hi @lekterable!

I quickly tried some things out.
I'm going to fix this by only supporting YouTube videos for now.

**Comment by MichaelDeBoey** [comment]
@all-contributors Please add @lekterable for bug

**Comment by MichaelDeBoey** [comment]
I've added #13 to track supporting YouTube channels.
