### ISSUE TITLE
GDPR compliance?

### ISSUE THREAD

**Issue by codegrau** [MichaelDeBoey/gatsby-remark-embedder#107]
How would I make this gdpr compliant like “click to load external ressources” before displaying the embedded iframes?

**Comment by MichaelDeBoey** [comment]
Hmmm that's a though one...

I'm afraid that's not possible at this moment and I don't think I want this in the scope of this plugin.
I _can_ tell you that all the transformers are using a `dnt` query param whenever we fetch the embed where possible.

https://github.com/MichaelDeBoey/gatsby-remark-embedder/blob/677c8ad0e918a3c69db490cd34c0748d6138f3a2/src/transformers/Twitter.js#L24

https://github.com/MichaelDeBoey/gatsby-remark-embedder/blob/677c8ad0e918a3c69db490cd34c0748d6138f3a2/src/transformers/YouTube.js#L34
