### ISSUE TITLE
Documentation: Services Options Explanation missing

### ISSUE THREAD

**Issue by wohfab** [MichaelDeBoey/gatsby-remark-embedder#113]
The documentation lacks information about the **[services options](https://github.com/MichaelDeBoey/gatsby-remark-embedder#services)**. It says, we can use options to manipulate the service, but does not give an example. I am trying to add options as follows:

```
{
  resolve: `gatsby-remark-embedder`,
  options: {
    services: {
      // I want to manipulate SoundCloud to change width and height:
      SoundCloud: {
        width: `50%`,
        height: `600`,
      }
    },
  },
},
```

This does not change anything in the embed.

**Comment by MichaelDeBoey** [comment]
Hey @wohfab!

That's normal, as there's no built-in transformer that supports options (yet).
As soon as a built-in transformer is supporting any option, we'll add them to the service-specific docs. 🙂

**Comment by wohfab** [comment]
Ah ok! Thanks a lot for the quick clarification. The specified part in the docs suggests (IMO), that those options already exist.

Sorry, I read that wrong.
