### ISSUE TITLE
Twitch transformer will not work after new Twitch requirements

### ISSUE THREAD

**Issue by FabioRosado** [MichaelDeBoey/gatsby-remark-embedder#128]
Hello, 

I've been working with the Twitch API for a month on another project and from time to time I go over to the forums and see if there are any new relevant topics. It seems that Twitch has changed their requirements on embedding videos and that is currently breaking a lot of embedding codes.

The change that Twitch has done is that it now requires you to pass a `&parent=<url>` parameter to the twitch embedder  url, this parent url has to be repeated for every domain that you use.  So if you are using netlify and a custom domain you will probably have to add two parents: `&parent=awesome-site.netlify.app&parent=awesome-site.io`. I'm saying probably since I haven't tested this out yet.

So on our Twitch Transformer we have to pickup our site url somehow and add it to the [getTwitchIFrameSrc function](https://github.com/MichaelDeBoey/gatsby-remark-embedder/blob/90ecaf872565681d1830b73421bd14801ab14bab/src/transformers/Twitch.js#L59)

---
**Reference:**
- [Embedding Videos and Clips Documentation](https://dev.twitch.tv/docs/embed/video-and-clips)
- [Thread about embedding on Wix sites](https://discuss.dev.twitch.tv/t/the-great-big-im-using-wix-and-i-dont-know-how-to-fix-my-embed-thread/26297)

**Comment by MichaelDeBoey** [comment]
So this means that we won't be able to have Twitch support on preview domains? 🤔

**Comment by MichaelDeBoey** [comment]
https://twitter.com/MichaelDeBoey93/status/1271762964090171392

**Comment by FabioRosado** [comment]
After reading the reply on Twitter, I was wondering if it might be possible to add the site url as a config option? 🤔  Might be a bit silly to have it for a single service but I'm trying to figure out how to make it work again

**Comment by MichaelDeBoey** [comment]
@FabioRosado Yeah I'm leaning towards a config option too, but then again it should be possible to set it dynamically somehow.
Don't see how that would be possible atm, since your gatsby website is already built (taking environment variables into account) before it's deployed to the dynamic subdomain.

**Comment by FabioRosado** [comment]
It also might be worth mention that on the forums and docs Twitch mentions that you should be able to use `localhost` as a parent for testing purposes, but I was unable to make the  iframe show the video. I'm assuming the reason might be because of the port on the url but when I add the port the iframe just says that the embed was misconfigured. Not sure if this will make  testing a pain.
