### ISSUE TITLE
Instagram returns 400 response about deprecated oEmbed endpoint

### ISSUE THREAD

**Issue by teeaarbee** [MichaelDeBoey/gatsby-remark-embedder#147]
- `gatsby-remark-embedder` version: "^3.0.0"
- `node` version: v10.16.2
- `npm` (or `yarn`) version: 6.9.0

Relevant code or config

```javascript

```

What you did:

What happened:

https://i.postimg.cc/sf8xKRkD/screenshot-2020-10-18.png
![image](https://user-images.githubusercontent.com/65780147/96369612-b8da6400-1178-11eb-81a0-575f0ae114f8.png)

Reproduction repository:
NA

Problem description: 
Unable to use instagram links 
```
The following error appeared while processing 'https://www.instagram.com/p/CGMMB_4HZgi/':
Request to https://api.instagram.com/oembed?url=https://www.instagram.com/p/CGMMB_4HZgi/&omitscript=true returned non-OK status (400)
```

Suggested solution:

**Comment by MichaelDeBoey** [comment]
Hi @teeaarbee! 👋

Can you please try without the trailing slash and see if that works?
I'm currently not at my computer to try it out myself.

**Comment by teeaarbee** [comment]
Hi @MichaelDeBoey i did  but still the same error, meanwhile I was looking at that error message and felt may be somethings wrong with the api response from IG and I see this on fb developers page:

![image](https://user-images.githubusercontent.com/65780147/96373589-2ee7c680-118b-11eb-9111-28aa7192e9c7.png)

```
The error code i see is 400 and the same status code mentioned in fb site
```
Is this something responsible for the error I see?
[https://developers.facebook.com/docs/instagram/oembed](https://developers.facebook.com/docs/instagram/oembed)

**Comment by MichaelDeBoey** [comment]
@teeaarbee It's weird that the endpoint is throwing `400` responses since the endpoint isn't deprecated (yet).
Although we should support the new API asap.

**Comment by MichaelDeBoey** [comment]
@all-contributors Please add @teeaarbee for bug
