### ISSUE TITLE
Add Support For CodePen

### ISSUE THREAD

**Issue by anuraghazra** [MichaelDeBoey/gatsby-remark-embedder#16]
I installed the plugin expecting that somehow codepen embeds will magically appear on my markdown, but i found out its not supported?

**Comment by MichaelDeBoey** [comment]
Hi @anuraghazra!

CodePen indeed isn't supported (yet).

Maybe I can try and have a look at it later this week. 😉

**Comment by MichaelDeBoey** [comment]
Note to self: visit https://codepen.io/embeds for more info

**Comment by anuraghazra** [comment]
Thanks for the fast reply.
That would be great to have codepen support, currently i'm using [gatsby-remark-codepen](https://www.gatsbyjs.org/packages/@weknow/gatsby-remark-codepen/) but i will switch to gatsby-remark-embedder because it has all the features i need, so i don't have to worry about different packages for YT, Twitter, Codepen etc
