### ISSUE TITLE
Support Gatsby v3

### ISSUE THREAD

**Issue by talohana** [MichaelDeBoey/gatsby-remark-embedder#175]
Gatsby v3 is officially out - https://github.com/gatsbyjs/gatsby/issues/29932. While migrating to v3 I'm getting error while running `npm install`:

> npm ERR! peer dep missing: gatsby@^2.20.0, required by gatsby-remark-embedder@4.1.0

Is there a way to test this plugin against gatsby v3?

I will be more than happy to submit a PR 🚀

**Comment by manhluong** [comment]
I installed this plugin via `--legacy-peer-deps` as in `npm install gatsby-remark-embedder --legacy-peer-deps` with Gatsby v3 and so far the youtube and twitter previews are working fine.
