### ISSUE TITLE
Support Gatsby v4

### ISSUE THREAD

**Issue by meehawk** [MichaelDeBoey/gatsby-remark-embedder#211]
I've been using this plugin ever since it came out and find it amazing. Recently upgraded to Gatsby v4. Was wondering if there were any plans to migrate this plugin to support Gatsby v4?

On a side note, I'd love to contribute and open a PR if need be and any guidance on this would be awesome

- `gatsby-remark-embedder` version: 5.0.0
- `node` version: 14.x
- `npm` version: 8.x

What you did:
Upgraded Gatsby to v4

What happened:

`warn Plugin gatsby-remark-embedder is not compatible with your gatsby version 4.1.6 - It requires gatsby@^3.0.0`

**Comment by trevorblades** [comment]
I just opened #214 to make this plugin compatible with Gatsby 4.

**Comment by anton-ivanov-feefo** [comment]
I have the same issue, would this fix be merged anytime soon?
