### ISSUE TITLE
Youtube link detection failed

### ISSUE THREAD

**Issue by anuraghazra** [MichaelDeBoey/gatsby-remark-embedder#23]
- `gatsby-remark-embedder` version: 1.3.1

What you did:
trying to embed youtube video with www.youtube.com

What happened:
did not embed

Problem description:
`https://youtube.com/watch?v=dQw4w9WgXcQ` is embedding correctly but `https://www.youtube.com/watch?v=dQw4w9WgXcQ` is not

Suggested solution:
Fixing `shouldTransform`  function

**Comment by anuraghazra** [comment]
looks like using === is causing the issue because it doesn't take account on `www`

```js
  return (
    host === 'youtu.be' ||
    (host === 'youtube.com' &&
      pathname.includes('/watch') &&
      Boolean(searchParams.get('v')))
  );
```

**Comment by MichaelDeBoey** [comment]
Hi @anuraghazra!

Thanks for bringing this to my attention.
Will push a fix asap. 🙂

**Comment by MichaelDeBoey** [comment]
@allcontributors Please add @anuraghazra for bugs

**Comment by anuraghazra** [comment]
so basically all **new URL(url).host === "my url"** checks will be failing in this case
