### ISSUE TITLE
Twitter embed creates blockquote inside p

### ISSUE THREAD

**Issue by alexluong** [MichaelDeBoey/gatsby-remark-embedder#41]
- `gatsby-remark-embedder` version: 1.5.0
- `node` version: 12
- `npm` (or `yarn`) version: yarn 1.19.1

What you did: Embed tweet inside MDX file

What happened:

2 error messages in the console:

```
Warning: validateDOMNesting(...): <p> cannot appear as a descendant of <p>.
```

 and 

```
Warning: validateDOMNesting(...): <blockquote> cannot appear as a descendant of <p>.
```

The reason is that the generated HTML for the tweet is:

```
<p>
  <blockquote>
    <p>Tweet content</p>
    ...
  </blockquote>
</p>
```

Suggested solution: I haven't looked into it yet. Just wanna report back. It's just an annoyance at the moment, no worries. I can help take a look when my schedule frees up a bit. Otherwise, hope you can provide a fix soon. Thank you!

**Comment by MichaelDeBoey** [comment]
Hi @alexluong!

Can you provide me with a reproduction repo/CodeSandbox please?

Thanks!

**Comment by alexluong** [comment]
@MichaelDeBoey I don't use `gatsby-plugin-twitter`. Should I?

FWIW, here are my Gatsby packages:

```
    "gatsby-plugin-mdx": "^1.0.57",
    "gatsby-plugin-sharp": "^2.3.2",
    "gatsby-plugin-theme-ui": "^0.2.43",
    "gatsby-plugin-typescript": "^2.1.19",
    "gatsby-remark-code-titles": "^1.1.0",
    "gatsby-remark-copy-linked-files": "^2.1.30",
    "gatsby-remark-embedder": "^1.5.0",
    "gatsby-remark-images": "^3.1.32",
    "gatsby-remark-smartypants": "^2.1.16",
    "gatsby-source-filesystem": "^2.1.38",
    "gatsby-transformer-sharp": "^2.3.5",
```

I will try to provide a reproduction soon.

**Comment by MichaelDeBoey** [comment]
@alexluong Like said in the README it's indeed necessary to use `gatsby-plugin-twitter` too when using the Twitter transformer
https://github.com/MichaelDeBoey/gatsby-remark-embedder#twitter

I think that'll fix the problem you're having (since the `blockquote` isn't the proper embed).

**Comment by MichaelDeBoey** [comment]
@alexloung Does that solve your problem? 🤔

**Comment by alexluong** [comment]
@MichaelDeBoey No, it doesn't. Instead of rendering the blockquote, it does render the Twitter embed (`twitter-widget`). However, the warnings are still there.

**Comment by MichaelDeBoey** [comment]
@alexluong You checked if this worked, so could you send me the repo/CodeSandbox which you used to check it out please?

If not public, can you please send me a private invite so I can investigate this a bit further?

I can't see any browser warnings (using Chrome) when going to [@kentcdodds' _Fix the slow render before you fix the re-render_ blogpost](https://kentcdodds.com/blog/fix-the-slow-render-before-you-fix-the-re-render) and inspect it and can't seem to reproduce it either,  so a reproduction would be really helpful in this case.

**Comment by MichaelDeBoey** [comment]
@alexluong Did you already find some time to look into an example? 🤔

**Comment by alexluong** [comment]
I'll have something for you this week!!

**Comment by MichaelDeBoey** [comment]
@alexluong Did you already find some time to look into an example? 🤔

**Comment by MichaelDeBoey** [comment]
Closed, because this one is stale.

@alexluong If you have more info, please open a new issue.
