### ISSUE TITLE
youtube embed not working once deployed to netlify

### ISSUE THREAD

**Issue by bradgarropy** [MichaelDeBoey/gatsby-remark-embedder#61]
- `gatsby-remark-embedder` version: `1.7.0`
- `node` version: `8.17.0`
- `npm` (or `yarn`) version: `6.13.4`

Relevant code or config

```javascript
// gatsby-config.js

{
    resolve: "gatsby-transformer-remark",
    options: {
        plugins: [
            {
                resolve: "gatsby-remark-images",
                options: {
                    maxWidth: 700,
                },
            },
            {
                resolve: "gatsby-remark-autolink-headers",
                options: {
                    maintainCase: false,
                    removeAccents: true,
                },
            },
            {
                resolve: "gatsby-remark-prismjs",
            },
            {
                resolve: "gatsby-remark-embedder",
            },
        ],
    },
},
```

```markdown
// post.md

https://youtu.be/ZL4NA9mXns8
```

What you did:
Pasted the above YouTube link into a Markdown document to be processed by `remark`, which should include `gatsby-remark-emedder`. Everything works great locally running `gatsby develop` and `gatsby build` with `node v12.13.1`. Then I pushed to Netlify where `gatsby build` [ran successfully](https://app.netlify.com/sites/bradgarropy/deploys/5e1eae6f5b060800c0fc65f8).

What happened:
The published site [does not embed](https://deploy-preview-103--bradgarropy.netlify.com/blog/adobe-lunch) the YouTube video successfully. There are no failed network requests or console errors.

Reproduction repository:
https://github.com/bradgarropy/bradgarropy.com/tree/66ce959721b485949e2d3ac3f87dfbef880a3d9a

Problem description:
YouTube embed not inserted when building on Netlify.

Suggested solution:
???

**Comment by bradgarropy** [comment]
Ah! Found out that Netlify's default version of Node.js is very old.
[Specifying a Node.js version](https://docs.netlify.com/configure-builds/manage-dependencies/#node-js-and-javascript) of `12` fixed the issue!

**Comment by bradgarropy** [comment]
Reopening as @MichaelDeBoey stated that this plugin should work with Node v8.

**Comment by MichaelDeBoey** [comment]
@bradgarropy It seems that the deploy worked with Node 8, no? 🤔
https://deploy-preview-103--bradgarropy.netlify.com/blog/adobe-lunch

**Comment by bradgarropy** [comment]
That was because I had set the `NODE_VERSION` environment variable to `12` in Netlify.
Here is a link to a [specific deploy](https://5e1eae6f5b060800c0fc65f8--bradgarropy.netlify.com/blog/adobe-lunch) that did not work as intended.

**Comment by MichaelDeBoey** [comment]
I'm going to close this one, since I'll release a major version with updated Node dependency.

**Comment by ilyamkin** [comment]
@MichaelDeBoey The issue with Node 8 in the `URL` object. If you import URL explicitly `const URL = require('url').URL;`, then the plugin would work.
I understand that you want to update Node with a major release, do you think it still makes sense to fix 1.x.x version as well compatibility wise? I can submit PR.

https://nodejs.org/es/blog/release/v8.0.0/#say-hello-to-the-whatwg-url-parser

**Comment by MichaelDeBoey** [comment]
@ilyamkin Hmmm that’s weird, ‘cause I think that part is just copied over from @kentcdodds’ website repo.
So that would mean the plugin never worked on Node 8.
But that should be impossible because we had tests for Twitter & YouTube from the start

**Comment by ilyamkin** [comment]
So I see the initial commit in this repo and it has `const { URL } = require('url')` which works in Node 8. 
https://github.com/MichaelDeBoey/gatsby-remark-embedder/blob/46bc578f7a6776974d6f1e76818ffac427cbe603/src/get-youtube-html.js#L1

**Comment by MichaelDeBoey** [comment]
@ilyamkin We still have a `import { URL } from 'url';` in each transformer file.

But in `index.js` we indeed rely on the global `URL`.
https://github.com/MichaelDeBoey/gatsby-remark-embedder/blob/2a16cd275a95246a4185b9aa184263cfc2dfd4f5/src/index.js#L9

I'm happy to accept a PR that fixes this if you want. 🙂

**Comment by MichaelDeBoey** [comment]
@all-contributors Please add @bradgarropy for bug
