### ISSUE TITLE
Instragram fails to transform

### ISSUE THREAD

**Issue by arryanggaputra** [MichaelDeBoey/gatsby-remark-embedder#67]
- `gatsby-remark-embedder` version: ^1.9.0
- `gatsby-plugin-instagram-embed` version: ^1.1.0
- `node` version: v13.6.0
- `npm`  version: 6.13.4

Relevant code or config
*gatsby-config.js*
```javascript
[
    `gatsby-plugin-instagram-embed`,
    {
      resolve: 'gatsby-transformer-remark',
      options: {
        plugins: [
          `gatsby-remark-embedder`
        ]
      }
    }
]
```

markdown
```markdown

I have done a funny work with this:

https://instagram.com/p/B60jPE6J8U-
```

What you did: Add instragram url to markdown file.

What happened:

```
 ERROR #85901  GRAPHQL

There was an error in your GraphQL query:

Cannot read property 'Symbol(Body internals)' of undefined

   1 | query CodeTipsPostByID($id: String!) {
   2 |   markdownRemark(id: {eq: $id}) {
   3 |     id
>  4 |     html
     |     ^
   5 |     frontmatter {
   6 |       date(formatString: "MMMM DD, YYYY")
   7 |       title
   8 |       description
   9 |       author
  10 |       tags
  11 |     }
  12 |   }
  13 | }
  14 |
```

**Comment by MichaelDeBoey** [comment]
Hi @arryanggaputra!

Could you provide a reproduction repo or CadeSandbox please, so I can take a look?

Thanks!

**Comment by arryanggaputra** [comment]
Hi @MichaelDeBoey 
This is the repo https://github.com/arryanggaputra/kopidev-gatsby/tree/development 
Last commit https://github.com/arryanggaputra/kopidev-gatsby/commit/8b12f347856b2bec8e2ea43a50ee3e8cf5ca382f

Thanks!

**Comment by MichaelDeBoey** [comment]
@arryanggaputra Can you update all your dependencies to the latest version please?
I know there was a problem in `gatsby`, which should be resolved.

**Comment by arryanggaputra** [comment]
@MichaelDeBoey  every dependency already upgrade to the latest version. 
```console
➜  my-gatsby git:(development) ✗ yarn outdated
yarn outdated v1.21.1
✨  Done in 1.90s.
```

Any other thing that I need to check?

**Comment by MichaelDeBoey** [comment]
@arryanggaputra Just checked out your repo and ran `yarn build` and I see it too.

Do you have the time to make a minimal representation please?
Just add `gatsby-transformer-remark` and `gatsby-remark-embedder` and you'll be good.
That way we can be sure it's not because of other things you're doing. 🙂

**Comment by MichaelDeBoey** [comment]
@all-contributors Please add @arryanggaputra for bug
