### ISSUE TITLE
intermittent network errors ( socket hang up )

### ISSUE THREAD

**Issue by pieh** [MichaelDeBoey/gatsby-remark-embedder#74]
- `gatsby-remark-embedder` version: `1.8.0`
- `node` version: `10.16.3`
- `npm` (or `yarn`) version: `yarn@1.17.3`

Relevant code or config

https://github.com/gatsbyjs/gatsby/blob/4b3ce3ee0f6bf2ae4b70a88ce19d78ee9e1e637b/www/gatsby-config.js#L139-L151

(usage with `gatsby-plugin-mdx` - probably not relavant)

What happened:

We are getting intermittent network errors when sourcing data for gatsbyjs.org resulting in logs like:

```
ERROR #11321  PLUGIN
"gatsby-plugin-mdx" threw an error while running the onCreateNode lifecycle:
request to https://publish.twitter.com/oembed?url=https://twitter.com/ryanflorence/status/906233888560758784&dnt=true&omit_script=true failed, reason: socket hang up
  FetchError: request to https://publish.twitter.com/oembed  ?url=https://twitter.com/ryanflorence/status/906233888560  758784&dnt=true&omit_script=true failed, reason: socket h  ang up
  - index.js:1455 ClientRequest.<anonymous>
    [www]/[node-fetch]/lib/index.js:1455:11
  - next_tick.js:63 process._tickCallback
    internal/process/next_tick.js:63:19
```

It's not particular embed specific - when it shows up it's usually different one. This doesn't happen every time, so it might be tricky to reproduce (might also depend on network condition)

Reproduction repository:

https://github.com/gatsbyjs/gatsby/tree/master/www

Suggested solution:

Implement retry mechanism in `fetchOEmbedData` helper function - https://github.com/MichaelDeBoey/gatsby-remark-embedder/blob/3fd14921c5c61ae4f48e317b506be6252ed0ea9b/src/transformers/utils/index.js#L3 to make the plugin more resilient to network failures

**Comment by MichaelDeBoey** [comment]
Hi @pieh!

Thanks for bringing this to my attention.

This is however a problem on your side.
Like you already mentioned, this is probably because of your network conditions.
https://github.com/node-fetch/node-fetch/issues/232

**Comment by pieh** [comment]
I do agree it's network related, but please note that this isn't just me that experiences this.

What i suggest here is to use maybe something like https://www.npmjs.com/package/fetch-retry to wrap `fetch` to give a chance to recover instead of failing build completely (which is just frustrating)

**Comment by MichaelDeBoey** [comment]
@pieh Can you send me some links to the other reports please?

**Comment by pieh** [comment]
Ah, they are not on github - I got those from our (gatsby) internal slack channel.

I wouldn't be bothered by it too much if it was just me or occasional hiccup for our learning/docs team (as most changes are content or components that don't require restarting `gatsby develop`), but it's primarily problem for @tesseralis who is working on enabling translations for gatsbyjs.org (which does require very often restarts due to changes to `gatsby-node.js`/`gatsby-config.js`)

**Comment by pieh** [comment]
I'm happy to provide PR for this - just didn't want to dive to deep before some chat here

**Comment by MichaelDeBoey** [comment]
Hmmm that's indeed annoying then.

One other problem would be that when there's no internet connection of course.

I'm happy to accept a PR if you want to implement it. 🙂
