### ISSUE TITLE
Use global URL whenever we drop Node 8 support

### ISSUE THREAD

**Issue by MichaelDeBoey** [MichaelDeBoey/gatsby-remark-embedder#82]
Remove all `import { URL } from 'url';` lines, because `URL` is globally available [since Node 10](https://nodejs.org/api/globals.html#globals_url).

Reference: #80

**Comment by acagastya** [comment]
But is there a reason to drop support for Node 8 anytime soon?

**Comment by MichaelDeBoey** [comment]
Node 8 is [EOL](https://nodejs.org/en/about/releases) & @gatsbyjs is going to drop official support [very soon](https://github.com/gatsbyjs/gatsby/pull/20343#issuecomment-572484387).

**Comment by pieh** [comment]
https://www.gatsbyjs.org/blog/2020-03-20-dropping-support-for-node-8/
