### ISSUE TITLE
allow title/linktext in links

### ISSUE THREAD

**Issue by muescha** [MichaelDeBoey/gatsby-remark-embedder#92]
Allow links with title, so that the transformer can use a title if needed:

```markdown
[Set up a Gatsby site](https://egghead.io/lessons/some-lesson)
```

**Comment by MichaelDeBoey** [comment]
Hi @muescha!

Just to be sure, what's the expected outcome you're looking for? 🤔
And why do you want it so badly?

**Comment by muescha** [comment]
for example for the EggHead Component has it. 
thats a good way to provide some a title or as an alt tag for aria

**Comment by MichaelDeBoey** [comment]
@muescha Why do you think it's necessary to add it?
What value does it have?

**Comment by muescha** [comment]
if hast the value that this plugin can handle also egghead embeds with a title.

the egghead component uses the title tag ([egghead-embed](https://github.com/gatsbyjs/gatsby/blob/master/www/src/components/shared/egghead-embed.js))

but you are right i see one drawback: then it is not that easy to distinct between "real" links and links who are needs to embedded.

**Comment by MichaelDeBoey** [comment]
Yeah the question we also have to ask ourselves is if it _really_ is necessary that we can set a correct title.
I'm not seeing any value in doing so tbh.

Maybe @kentcdodds can sway in with his opinion too? 🤔

**Comment by muescha** [comment]
i think it is in the gatsby repo because of accessibility 
(https://dequeuniversity.com/tips/provide-iframe-titles)

i think the other transformers can also benefit from more accessibility

**Comment by muescha** [comment]
```markdown
## Other resources

- [Egghead.io Course: Gatsby Theme Authoring (free)](https://egghead.io/courses/gatsby-theme-authoring)
- [Setting up yarn workspaces for Gatsby theme development](/blog/2019-05-22-setting-up-yarn-workspaces-for-theme-development/#reach-skip-nav)
- [What is component shadowing?](/blog/2019-04-29-component-shadowing/)
- [Customizing styles in Gatsby themes with Theme-UI](/blog/2019-07-03-customizing-styles-in-gatsby-themes-with-theme-ui/)
- [Composing and styling Gatsby themes (with Brent Jackson) — Learn With Jason](https://www.youtube.com/watch?v=6Z4p-qjnKCQ)
- [Build a Personal Site Using Gatsby Themes (with Will Johnson) — Learn With Jason](https://www.youtube.com/watch?v=vf2Dy_xKUno)
```

or in lists like this:
https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/awesome-gatsby-resources.md#L62-L65

**Comment by MichaelDeBoey** [comment]
The list you're providing is just meant to be a list, not all embeds.
So I think the plugin is doing what it should do, no? 🤔

**Comment by muescha** [comment]
Sorry I forget to add this: 
the examples are against my suggestion. That means adding a title is not a good idea because of the syntax :(

**Comment by muescha** [comment]
an other syntax suggestion: maybe with a blockquote `>`

```markdown

> [Set up a Gatsby site](https://egghead.io/lessons/some-lesson)

```

**Comment by MichaelDeBoey** [comment]
> an other syntax suggestion: maybe with a blockquote `>`

What about when people have a quote with a link in it? 🤔

**Comment by muescha** [comment]
the same if just the url as text is in a paragraph 🤔

**Comment by MichaelDeBoey** [comment]
That's true indeed.

Going to close this one, as it's clear that this isn't really something that would be possible.
